apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: astartebot
  name: astartebot
  namespace: astartebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astartebot
  strategy: {}
  template:
    metadata:
      labels:
        app: astartebot
    spec:
      containers:
      - image: ghcr.io/bdomars/astartebot
        imagePullPolicy: Always
        name: astartebot
        resources: {}
        ports:
        - containerPort: 8080
          name: webhook
          protocol: TCP
        envFrom:
        - configMapRef:
            name: astartebot
---
apiVersion: v1
kind: Service
metadata:
  name: astartebot
  namespace: astartebot
spec:
  ports:
  - name: webhook
    port: 8080
    protocol: TCP
  selector:
    app: astartebot
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: astartebot
  namespace: astartebot
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`tghook.0xbd.fi`)
    services:
    - kind: Service
      name: astartebot
      port: 8080
  tls:
    certResolver: dns0xbd
